### ISSUE TITLE
Error to import dependency (Invalid plugin specification flavorbanner)

### ISSUE THREAD

**Issue by mdeandrea-mrmilu** [p02diada/flutter-flavor-banner#7]
## Environment

**Version:** 2.0.0
**Device information:** All

## Description

**Expected behavior:**
Get dependency

**Current behavior:**
flutter pub get
Invalid plugin specification flavorbanner.
Invalid "android" plugin specification.
Invalid "ios" plugin specification.

## Steps to reproduce

1. add `flavorbanner: 2.0.0` to pubspec
2. run `flutter pub get`
3. Get error

Flutter doctor:
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-ES)
    • Flutter version 2.5.3 at /Users/matias/fvm/versions/2.5.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

**Comment by p02diada** [comment]
fixed in 2.0.1 release
